# Generated by Django 3.2.11 on 2022-01-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_pk',
            field=models.IntegerField(null=True),
        ),
    ]
