# Generated by Django 3.2.11 on 2022-01-16 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('contents', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('publish_date', models.DateField(auto_now=True)),
                ('travel_date', models.DateField()),
                ('city', models.CharField(max_length=20)),
                ('expense', models.PositiveIntegerField()),
                ('place', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', related_query_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug'], name='posts_post_slug_59b922_idx'),
        ),
    ]
