# Generated by Django 3.2.11 on 2022-01-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220117_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='travel_date',
            field=models.TextField(),
        ),
    ]
